/*
Package scanner
初始化许可证全名转简写
许可证全名转简写
检查许可证冲突
推荐不与模块许可证冲突的项目许可证
*/
package scanner

import "strings"

// LicensePair 许可证对
type LicensePair struct {
	// mainLicense 项目许可证
	mainLicense string
	// libLicense 依赖的库的许可证
	libLicense string
}

var pass = "相容"
var fail = "冲突"
var unknown = "分析失败，许可证库不包含对应信息"

var licenseArr = [...]string{"LGPL-2.1-only", "LGPL-2.1-or-later", "LGPL-3.0-only", "GPL-2.0-only",
	"GPL-2.0-or-later", "GPL-3.0-only", "AGPL-3.0-only", "Artistic-2.0", "CECILL-2.1", "EPL-1.0",
	"EPL-2.0", "EUPL-1.1", "EUPL-1.2", "MPL-2.0", "MS-RL", "OSL-3.0", "Vim", "CDDL-1.0", "CPAL-1.0",
	"CPL-1.0", "IPL-1.0", "LPL-1.02", "Nokia", "RPSL-1.0", "SISSL", "Sleepycat", "SPL-1.0",
	"php-3.01", "Apache-2.0", "ECL-2.0"}

var licenseLongToShort = map[string]string{
	"GNU Lesser General Public License v2.1 only": "LGPL-2.1-only",
	//此文本无法分辨是only还是or-later，暂归类为or-later
	"GNU LESSER GENERAL PUBLIC LICENSE Version 2.1":   "LGPL-2.1-or-later",
	"GNU Lesser General Public License v2.1 or later": "LGPL-2.1-or-later",
	"GNU LESSER GENERAL PUBLIC LICENSE Version 3":     "LGPL-3.0-only",
	"GNU Lesser General Public License v3.0 only":     "LGPL-3.0-only",
	"GNU General Public License v2.0 only":            "GPL-2.0-only",
	//此文本无法分辨是only还是or-later，暂归类为or-later
	"GNU GENERAL PUBLIC LICENSE Version 2":     "GPL-2.0-or-later",
	"GNU General Public License v2.0 or later": "GPL-2.0-or-later",
	"GNU General Public License v3.0 only":     "GPL-3.0-only",
	//此文本无法分辨是only还是or-later，暂归类为only
	"GNU GENERAL PUBLIC LICENSE Version 3":        "GPL-3.0-only",
	"GNU Affero General Public License v3.0 only": "AGPL-3.0-only",
	//此文本无法分辨是only还是or-later，暂归类为only
	"GNU AFFERO GENERAL PUBLIC LICENSE Version 3":                       "AGPL-3.0-only",
	"Artistic License 2.0":                                              "Artistic-2.0",
	"The Artistic License 2.0":                                          "Artistic-2.0",
	"CeCILL Free Software License Agreement v2.1":                       "CECILL-2.1",
	"CeCILL FREE SOFTWARE LICENSE AGREEMENT Version 2.1":                "CECILL-2.1",
	"Eclipse Public License 1.0":                                        "EPL-1.0",
	"Eclipse Public License - v 1.0":                                    "EPL-1.0",
	"Eclipse Public License 2.0":                                        "EPL-2.0",
	"Eclipse Public License - v 2.0":                                    "EPL-2.0",
	"European Union Public License 1.1":                                 "EUPL-1.1",
	"European Union Public Licence V. 1.1":                              "EUPL-1.1",
	"European Union Public License 1.2":                                 "EUPL-1.2",
	"European Union Public Licence v. 1.2":                              "EUPL-1.2",
	"Mozilla Public License 2.0":                                        "MPL-2.0",
	"Mozilla Public License Version 2.0":                                "MPL-2.0",
	"Microsoft Reciprocal License":                                      "MS-RL",
	"Microsoft Reciprocal License (Ms-RL)":                              "MS-RL",
	"Open Software License 3.0":                                         "OSL-3.0",
	"Open Software License v. 3.0":                                      "OSL-3.0",
	"Vim License":                                                       "Vim",
	"VIM LICENSE":                                                       "Vim",
	"Common Development and Distribution License 1.0":                   "CDDL-1.0",
	"COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0":    "CDDL-1.0",
	"Common Public Attribution License 1.0":                             "CPAL-1.0",
	"Common Public Attribution License Version 1.0 (CPAL)":              "CPAL-1.0",
	"Common Public License 1.0":                                         "CPL-1.0",
	"Common Public License Version 1.0":                                 "CPL-1.0",
	"IBM Public License v1.0":                                           "IPL-1.0",
	"IBM Public License Version 1.0":                                    "IPL-1.0",
	"Lucent Public License v1.02":                                       "LPL-1.02",
	"Lucent Public License Version 1.02":                                "LPL-1.02",
	"Nokia Open Source License":                                         "Nokia",
	"Nokia Open Source License (NOKOS License)":                         "Nokia",
	"RealNetworks Public Source License v1.0":                           "RPSL-1.0",
	"RealNetworks Public Source License Version 1.0":                    "RPSL-1.0",
	"Sun Industry Standards Source License v1.1":                        "SISSL",
	"Sun Industry Standards Source License - Version 1.1":               "SISSL",
	"Sleepycat License":                                                 "Sleepycat",
	"The Sleepycat License Copyright (c) 1990-1999 Sleepycat Software.": "Sleepycat",
	"Sun Public License v1.0":                                           "SPL-1.0",
	"SUN PUBLIC LICENSE Version 1.0":                                    "SPL-1.0",
	"PHP License v3.01":                                                 "php-3.01",
	"The PHP License, version 3.01":                                     "php-3.01",
	"Apache License 2.0":                                                "Apache-2.0",
	"Apache License Version 2.0":                                        "Apache-2.0",
	"Educational Community License v2.0":                                "ECL-2.0",
	"Educational Community License Version 2.0":                         "ECL-2.0",
}

// licenseConflictBaseMap 记录项目所使用许可证与项目所依赖的库的许可证之间的关系
var licenseConflictBaseMap = map[LicensePair]string{
	LicensePair{"LGPL-2.1-only", "LGPL-2.1-only"}:         pass,
	LicensePair{"LGPL-2.1-only", "LGPL-2.1-or-later"}:     pass,
	LicensePair{"LGPL-2.1-only", "LGPL-3.0-only"}:         pass,
	LicensePair{"LGPL-2.1-only", "GPL-2.0-only"}:          fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"LGPL-2.1-only", "GPL-2.0-or-later"}:      fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"LGPL-2.1-only", "GPL-3.0-only"}:          fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"LGPL-2.1-only", "AGPL-3.0-only"}:         fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"LGPL-2.1-only", "Artistic-2.0"}:          pass,
	LicensePair{"LGPL-2.1-only", "CECILL-2.1"}:            fail,
	LicensePair{"LGPL-2.1-only", "EPL-1.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "EPL-2.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "EUPL-1.1"}:              fail,
	LicensePair{"LGPL-2.1-only", "EUPL-1.2"}:              pass,
	LicensePair{"LGPL-2.1-only", "MPL-2.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "MS-RL"}:                 fail,
	LicensePair{"LGPL-2.1-only", "ODbL-1.0"}:              fail,
	LicensePair{"LGPL-2.1-only", "OSL-3.0"}:               fail,
	LicensePair{"LGPL-2.1-only", "Vim"}:                   fail,
	LicensePair{"LGPL-2.1-only", "CDDL-1.0"}:              pass,
	LicensePair{"LGPL-2.1-only", "CPAL-1.0"}:              pass,
	LicensePair{"LGPL-2.1-only", "CPL-1.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "IPL-1.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "LPL-1.02"}:              fail,
	LicensePair{"LGPL-2.1-only", "Nokia"}:                 pass,
	LicensePair{"LGPL-2.1-only", "RPSL-1.0"}:              fail + ", 并入的代码遵循LGPL-2.1-only",
	LicensePair{"LGPL-2.1-only", "SISSL"}:                 pass,
	LicensePair{"LGPL-2.1-only", "Sleepycat"}:             fail + ", 并入的代码遵循LGPL-2.1-only",
	LicensePair{"LGPL-2.1-only", "SPL-1.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "Apache-2.0"}:            pass,
	LicensePair{"LGPL-2.1-only", "ECL-2.0"}:               pass,
	LicensePair{"LGPL-2.1-only", "php-3.01"}:              fail,
	LicensePair{"LGPL-2.1-or-later", "LGPL-2.1-only"}:     pass,
	LicensePair{"LGPL-2.1-or-later", "LGPL-2.1-or-later"}: pass,
	LicensePair{"LGPL-2.1-or-later", "LGPL-3.0-only"}:     pass,
	LicensePair{"LGPL-2.1-or-later", "GPL-2.0-only"}:      fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"LGPL-2.1-or-later", "GPL-2.0-or-later"}:  fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"LGPL-2.1-or-later", "GPL-3.0-only"}:      fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"LGPL-2.1-or-later", "AGPL-3.0-only"}:     fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"LGPL-2.1-or-later", "Artistic-2.0"}:      pass,
	LicensePair{"LGPL-2.1-or-later", "CECILL-2.1"}:        fail,
	LicensePair{"LGPL-2.1-or-later", "EPL-1.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "EPL-2.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "EUPL-1.1"}:          fail,
	LicensePair{"LGPL-2.1-or-later", "EUPL-1.2"}:          pass,
	LicensePair{"LGPL-2.1-or-later", "MPL-2.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "MS-RL"}:             fail,
	LicensePair{"LGPL-2.1-or-later", "ODbL-1.0"}:          fail,
	LicensePair{"LGPL-2.1-or-later", "OSL-3.0"}:           fail,
	LicensePair{"LGPL-2.1-or-later", "Vim"}:               fail,
	LicensePair{"LGPL-2.1-or-later", "CDDL-1.0"}:          pass,
	LicensePair{"LGPL-2.1-or-later", "CPAL-1.0"}:          pass,
	LicensePair{"LGPL-2.1-or-later", "CPL-1.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "IPL-1.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "LPL-1.02"}:          fail,
	LicensePair{"LGPL-2.1-or-later", "Nokia"}:             pass,
	LicensePair{"LGPL-2.1-or-later", "RPSL-1.0"}:          fail + ", 并入的代码遵循LGPL-2.1-or-later",
	LicensePair{"LGPL-2.1-or-later", "SISSL"}:             pass,
	LicensePair{"LGPL-2.1-or-later", "Sleepycat"}:         fail + ", 并入的代码遵循LGPL-2.1-or-later",
	LicensePair{"LGPL-2.1-or-later", "SPL-1.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "Apache-2.0"}:        pass,
	LicensePair{"LGPL-2.1-or-later", "ECL-2.0"}:           pass,
	LicensePair{"LGPL-2.1-or-later", "php-3.01"}:          fail,
	LicensePair{"LGPL-3.0-only", "LGPL-2.1-only"}:         pass,
	LicensePair{"LGPL-3.0-only", "LGPL-2.1-or-later"}:     pass,
	LicensePair{"LGPL-3.0-only", "LGPL-3.0-only"}:         pass,
	LicensePair{"LGPL-3.0-only", "GPL-2.0-only"}:          fail,
	LicensePair{"LGPL-3.0-only", "GPL-2.0-or-later"}:      fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"LGPL-3.0-only", "GPL-3.0-only"}:          fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"LGPL-3.0-only", "AGPL-3.0-only"}:         fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"LGPL-3.0-only", "Artistic-2.0"}:          pass,
	LicensePair{"LGPL-3.0-only", "CECILL-2.1"}:            fail,
	LicensePair{"LGPL-3.0-only", "EPL-1.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "EPL-2.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "EUPL-1.1"}:              fail,
	LicensePair{"LGPL-3.0-only", "EUPL-1.2"}:              pass,
	LicensePair{"LGPL-3.0-only", "MPL-2.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "MS-RL"}:                 fail,
	LicensePair{"LGPL-3.0-only", "ODbL-1.0"}:              fail,
	LicensePair{"LGPL-3.0-only", "OSL-3.0"}:               fail,
	LicensePair{"LGPL-3.0-only", "Vim"}:                   fail,
	LicensePair{"LGPL-3.0-only", "CDDL-1.0"}:              pass,
	LicensePair{"LGPL-3.0-only", "CPAL-1.0"}:              pass,
	LicensePair{"LGPL-3.0-only", "CPL-1.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "IPL-1.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "LPL-1.02"}:              fail,
	LicensePair{"LGPL-3.0-only", "Nokia"}:                 pass,
	LicensePair{"LGPL-3.0-only", "RPSL-1.0"}:              fail + ", 并入的代码遵循LGPL-3.0-only",
	LicensePair{"LGPL-3.0-only", "SISSL"}:                 pass,
	LicensePair{"LGPL-3.0-only", "Sleepycat"}:             fail + ", 并入的代码遵循LGPL-3.0-only",
	LicensePair{"LGPL-3.0-only", "SPL-1.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "Apache-2.0"}:            pass,
	LicensePair{"LGPL-3.0-only", "ECL-2.0"}:               pass,
	LicensePair{"LGPL-3.0-only", "php-3.01"}:              fail,
	LicensePair{"GPL-2.0-only", "LGPL-2.1-only"}:          pass,
	LicensePair{"GPL-2.0-only", "LGPL-2.1-or-later"}:      pass,
	LicensePair{"GPL-2.0-only", "LGPL-3.0-only"}:          fail,
	LicensePair{"GPL-2.0-only", "GPL-2.0-only"}:           pass,
	LicensePair{"GPL-2.0-only", "GPL-2.0-or-later"}:       pass,
	LicensePair{"GPL-2.0-only", "GPL-3.0-only"}:           fail,
	LicensePair{"GPL-2.0-only", "AGPL-3.0-only"}:          fail,
	LicensePair{"GPL-2.0-only", "Artistic-2.0"}:           pass,
	LicensePair{"GPL-2.0-only", "CECILL-2.1"}:             pass,
	LicensePair{"GPL-2.0-only", "EPL-1.0"}:                pass,
	LicensePair{"GPL-2.0-only", "EPL-2.0"}:                pass,
	LicensePair{"GPL-2.0-only", "EUPL-1.1"}:               pass,
	LicensePair{"GPL-2.0-only", "EUPL-1.2"}:               pass,
	LicensePair{"GPL-2.0-only", "MPL-2.0"}:                pass,
	LicensePair{"GPL-2.0-only", "MS-RL"}:                  fail,
	LicensePair{"GPL-2.0-only", "ODbL-1.0"}:               fail,
	LicensePair{"GPL-2.0-only", "OSL-3.0"}:                fail,
	LicensePair{"GPL-2.0-only", "Vim"}:                    pass,
	LicensePair{"GPL-2.0-only", "CDDL-1.0"}:               pass,
	LicensePair{"GPL-2.0-only", "CPAL-1.0"}:               pass,
	LicensePair{"GPL-2.0-only", "CPL-1.0"}:                pass,
	LicensePair{"GPL-2.0-only", "IPL-1.0"}:                pass,
	LicensePair{"GPL-2.0-only", "LPL-1.02"}:               fail,
	LicensePair{"GPL-2.0-only", "Nokia"}:                  pass,
	LicensePair{"GPL-2.0-only", "RPSL-1.0"}:               fail + ", 并入的代码遵循GPL-2.0-only",
	LicensePair{"GPL-2.0-only", "SISSL"}:                  pass,
	LicensePair{"GPL-2.0-only", "Sleepycat"}:              fail + ", 并入的代码遵循GPL-2.0-only",
	LicensePair{"GPL-2.0-only", "SPL-1.0"}:                pass,
	LicensePair{"GPL-2.0-only", "Apache-2.0"}:             fail,
	LicensePair{"GPL-2.0-only", "ECL-2.0"}:                fail,
	LicensePair{"GPL-2.0-only", "php-3.01"}:               fail,
	LicensePair{"GPL-2.0-or-later", "LGPL-2.1-only"}:      pass,
	LicensePair{"GPL-2.0-or-later", "LGPL-2.1-or-later"}:  pass,
	LicensePair{"GPL-2.0-or-later", "LGPL-3.0-only"}:      fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"GPL-2.0-or-later", "GPL-2.0-only"}:       fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"GPL-2.0-or-later", "GPL-2.0-or-later"}:   pass,
	LicensePair{"GPL-2.0-or-later", "GPL-3.0-only"}:       pass,
	LicensePair{"GPL-2.0-or-later", "AGPL-3.0-only"}:      fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"GPL-2.0-or-later", "Artistic-2.0"}:       pass,
	LicensePair{"GPL-2.0-or-later", "CECILL-2.1"}:         pass,
	LicensePair{"GPL-2.0-or-later", "EPL-1.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "EPL-2.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "EUPL-1.1"}:           fail,
	LicensePair{"GPL-2.0-or-later", "EUPL-1.2"}:           pass,
	LicensePair{"GPL-2.0-or-later", "MPL-2.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "MS-RL"}:              fail,
	LicensePair{"GPL-2.0-or-later", "ODbL-1.0"}:           fail,
	LicensePair{"GPL-2.0-or-later", "OSL-3.0"}:            fail,
	LicensePair{"GPL-2.0-or-later", "Vim"}:                pass,
	LicensePair{"GPL-2.0-or-later", "CDDL-1.0"}:           pass,
	LicensePair{"GPL-2.0-or-later", "CPAL-1.0"}:           pass,
	LicensePair{"GPL-2.0-or-later", "CPL-1.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "IPL-1.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "LPL-1.02"}:           fail,
	LicensePair{"GPL-2.0-or-later", "Nokia"}:              pass,
	LicensePair{"GPL-2.0-or-later", "RPSL-1.0"}:           fail + ", 并入的代码遵循GPL-2.0-or-later",
	LicensePair{"GPL-2.0-or-later", "SISSL"}:              pass,
	LicensePair{"GPL-2.0-or-later", "Sleepycat"}:          fail + ", 并入的代码遵循GPL-2.0-or-later",
	LicensePair{"GPL-2.0-or-later", "SPL-1.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "Apache-2.0"}:         pass,
	LicensePair{"GPL-2.0-or-later", "ECL-2.0"}:            pass,
	LicensePair{"GPL-2.0-or-later", "php-3.01"}:           fail,
	LicensePair{"GPL-3.0-only", "LGPL-2.1-only"}:          pass,
	LicensePair{"GPL-3.0-only", "LGPL-2.1-or-later"}:      pass,
	LicensePair{"GPL-3.0-only", "LGPL-3.0-only"}:          pass,
	LicensePair{"GPL-3.0-only", "GPL-2.0-only"}:           fail,
	LicensePair{"GPL-3.0-only", "GPL-2.0-or-later"}:       pass,
	LicensePair{"GPL-3.0-only", "GPL-3.0-only"}:           pass,
	LicensePair{"GPL-3.0-only", "AGPL-3.0-only"}:          fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"GPL-3.0-only", "Artistic-2.0"}:           pass,
	LicensePair{"GPL-3.0-only", "CECILL-2.1"}:             pass,
	LicensePair{"GPL-3.0-only", "EPL-1.0"}:                pass,
	LicensePair{"GPL-3.0-only", "EPL-2.0"}:                pass,
	LicensePair{"GPL-3.0-only", "EUPL-1.1"}:               fail,
	LicensePair{"GPL-3.0-only", "EUPL-1.2"}:               pass,
	LicensePair{"GPL-3.0-only", "MPL-2.0"}:                pass,
	LicensePair{"GPL-3.0-only", "MS-RL"}:                  fail,
	LicensePair{"GPL-3.0-only", "ODbL-1.0"}:               fail,
	LicensePair{"GPL-3.0-only", "OSL-3.0"}:                fail,
	LicensePair{"GPL-3.0-only", "Vim"}:                    pass,
	LicensePair{"GPL-3.0-only", "CDDL-1.0"}:               pass,
	LicensePair{"GPL-3.0-only", "CPAL-1.0"}:               pass,
	LicensePair{"GPL-3.0-only", "CPL-1.0"}:                pass,
	LicensePair{"GPL-3.0-only", "IPL-1.0"}:                pass,
	LicensePair{"GPL-3.0-only", "LPL-1.02"}:               fail,
	LicensePair{"GPL-3.0-only", "Nokia"}:                  pass,
	LicensePair{"GPL-3.0-only", "RPSL-1.0"}:               fail + ", 并入的代码遵循GPL-3.0-only",
	LicensePair{"GPL-3.0-only", "SISSL"}:                  pass,
	LicensePair{"GPL-3.0-only", "Sleepycat"}:              fail + ", 并入的代码遵循GPL-3.0-only",
	LicensePair{"GPL-3.0-only", "SPL-1.0"}:                pass,
	LicensePair{"GPL-3.0-only", "Apache-2.0"}:             pass,
	LicensePair{"GPL-3.0-only", "ECL-2.0"}:                pass,
	LicensePair{"GPL-3.0-only", "php-3.01"}:               fail,
	LicensePair{"AGPL-3.0-only", "LGPL-2.1-only"}:         pass,
	LicensePair{"AGPL-3.0-only", "LGPL-2.1-or-later"}:     pass,
	LicensePair{"AGPL-3.0-only", "LGPL-3.0-only"}:         pass,
	LicensePair{"AGPL-3.0-only", "GPL-2.0-only"}:          fail,
	LicensePair{"AGPL-3.0-only", "GPL-2.0-or-later"}:      pass,
	LicensePair{"AGPL-3.0-only", "GPL-3.0-only"}:          pass,
	LicensePair{"AGPL-3.0-only", "AGPL-3.0-only"}:         pass,
	LicensePair{"AGPL-3.0-only", "Artistic-2.0"}:          pass,
	LicensePair{"AGPL-3.0-only", "CECILL-2.1"}:            pass,
	LicensePair{"AGPL-3.0-only", "EPL-1.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "EPL-2.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "EUPL-1.1"}:              fail,
	LicensePair{"AGPL-3.0-only", "EUPL-1.2"}:              pass,
	LicensePair{"AGPL-3.0-only", "MPL-2.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "MS-RL"}:                 fail,
	LicensePair{"AGPL-3.0-only", "ODbL-1.0"}:              fail,
	LicensePair{"AGPL-3.0-only", "OSL-3.0"}:               fail,
	LicensePair{"AGPL-3.0-only", "Vim"}:                   pass,
	LicensePair{"AGPL-3.0-only", "CDDL-1.0"}:              pass,
	LicensePair{"AGPL-3.0-only", "CPAL-1.0"}:              pass,
	LicensePair{"AGPL-3.0-only", "CPL-1.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "IPL-1.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "LPL-1.02"}:              fail,
	LicensePair{"AGPL-3.0-only", "Nokia"}:                 pass,
	LicensePair{"AGPL-3.0-only", "RPSL-1.0"}:              fail + ", 并入的代码遵循AGPL-3.0-only",
	LicensePair{"AGPL-3.0-only", "SISSL"}:                 pass,
	LicensePair{"AGPL-3.0-only", "Sleepycat"}:             fail + ", 并入的代码遵循LGPL-3.0-only",
	LicensePair{"AGPL-3.0-only", "SPL-1.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "Apache-2.0"}:            pass,
	LicensePair{"AGPL-3.0-only", "ECL-2.0"}:               pass,
	LicensePair{"AGPL-3.0-only", "php-3.01"}:              fail,
	LicensePair{"Artistic-2.0", "LGPL-2.1-only"}:          pass,
	LicensePair{"Artistic-2.0", "LGPL-2.1-or-later"}:      pass,
	LicensePair{"Artistic-2.0", "LGPL-3.0-only"}:          pass,
	LicensePair{"Artistic-2.0", "GPL-2.0-only"}:           fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"Artistic-2.0", "GPL-2.0-or-later"}:       fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"Artistic-2.0", "GPL-3.0-only"}:           fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"Artistic-2.0", "AGPL-3.0-only"}:          fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"Artistic-2.0", "Artistic-2.0"}:           pass,
	LicensePair{"Artistic-2.0", "CECILL-2.1"}:             fail + ", 组合遵循CECILL-2.1",
	LicensePair{"Artistic-2.0", "EPL-1.0"}:                pass,
	LicensePair{"Artistic-2.0", "EPL-2.0"}:                pass,
	LicensePair{"Artistic-2.0", "EUPL-1.1"}:               fail + ", 组合遵循EUPL-1.1",
	LicensePair{"Artistic-2.0", "EUPL-1.2"}:               fail + ", 组合遵循EUPL-1.2",
	LicensePair{"Artistic-2.0", "MPL-2.0"}:                pass,
	LicensePair{"Artistic-2.0", "MS-RL"}:                  fail + ", 组合遵循MS-RL",
	LicensePair{"Artistic-2.0", "ODbL-1.0"}:               fail + ", 组合遵循ODbL-1.0",
	LicensePair{"Artistic-2.0", "OSL-3.0"}:                fail + ", 组合遵循OSL-3.0",
	LicensePair{"Artistic-2.0", "Vim"}:                    fail + ", 组合遵循Vim",
	LicensePair{"Artistic-2.0", "CDDL-1.0"}:               pass,
	LicensePair{"Artistic-2.0", "CPAL-1.0"}:               pass,
	LicensePair{"Artistic-2.0", "CPL-1.0"}:                pass,
	LicensePair{"Artistic-2.0", "IPL-1.0"}:                pass,
	LicensePair{"Artistic-2.0", "LPL-1.02"}:               pass,
	LicensePair{"Artistic-2.0", "Nokia"}:                  pass,
	LicensePair{"Artistic-2.0", "RPSL-1.0"}:               pass,
	LicensePair{"Artistic-2.0", "SISSL"}:                  pass,
	LicensePair{"Artistic-2.0", "Sleepycat"}:              fail + ", 组合遵循Sleepycat",
	LicensePair{"Artistic-2.0", "SPL-1.0"}:                pass,
	LicensePair{"Artistic-2.0", "Apache-2.0"}:             pass,
	LicensePair{"Artistic-2.0", "ECL-2.0"}:                pass,
	LicensePair{"Artistic-2.0", "php-3.01"}:               pass,
	LicensePair{"CECILL-2.1", "LGPL-2.1-only"}:            pass,
	LicensePair{"CECILL-2.1", "LGPL-2.1-or-later"}:        pass,
	LicensePair{"CECILL-2.1", "LGPL-3.0-only"}:            pass,
	LicensePair{"CECILL-2.1", "GPL-2.0-only"}:             fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"CECILL-2.1", "GPL-2.0-or-later"}:         fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"CECILL-2.1", "GPL-3.0-only"}:             fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"CECILL-2.1", "AGPL-3.0-only"}:            fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"CECILL-2.1", "Artistic-2.0"}:             pass,
	LicensePair{"CECILL-2.1", "CECILL-2.1"}:               pass,
	LicensePair{"CECILL-2.1", "EPL-1.0"}:                  pass,
	LicensePair{"CECILL-2.1", "EPL-2.0"}:                  pass,
	LicensePair{"CECILL-2.1", "EUPL-1.1"}:                 fail + ", 组合遵循EUPL-1.1",
	LicensePair{"CECILL-2.1", "EUPL-1.2"}:                 pass,
	LicensePair{"CECILL-2.1", "MPL-2.0"}:                  pass,
	LicensePair{"CECILL-2.1", "MS-RL"}:                    fail,
	LicensePair{"CECILL-2.1", "ODbL-1.0"}:                 fail,
	LicensePair{"CECILL-2.1", "OSL-3.0"}:                  fail,
	LicensePair{"CECILL-2.1", "Vim"}:                      fail,
	LicensePair{"CECILL-2.1", "CDDL-1.0"}:                 pass,
	LicensePair{"CECILL-2.1", "CPAL-1.0"}:                 pass,
	LicensePair{"CECILL-2.1", "CPL-1.0"}:                  pass,
	LicensePair{"CECILL-2.1", "IPL-1.0"}:                  pass,
	LicensePair{"CECILL-2.1", "LPL-1.02"}:                 fail + ", 并入的代码遵循CECILL-2.1",
	LicensePair{"CECILL-2.1", "Nokia"}:                    pass,
	LicensePair{"CECILL-2.1", "RPSL-1.0"}:                 fail,
	LicensePair{"CECILL-2.1", "SISSL"}:                    pass,
	LicensePair{"CECILL-2.1", "Sleepycat"}:                fail,
	LicensePair{"CECILL-2.1", "SPL-1.0"}:                  pass,
	LicensePair{"CECILL-2.1", "Apache-2.0"}:               pass,
	LicensePair{"CECILL-2.1", "ECL-2.0"}:                  pass,
	LicensePair{"CECILL-2.1", "php-3.01"}:                 pass,
	LicensePair{"EPL-1.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"EPL-1.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"EPL-1.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"EPL-1.0", "GPL-2.0-only"}:                fail,
	LicensePair{"EPL-1.0", "GPL-2.0-or-later"}:            fail,
	LicensePair{"EPL-1.0", "GPL-3.0-only"}:                fail,
	LicensePair{"EPL-1.0", "AGPL-3.0-only"}:               fail,
	LicensePair{"EPL-1.0", "Artistic-2.0"}:                pass,
	LicensePair{"EPL-1.0", "CECILL-2.1"}:                  fail,
	LicensePair{"EPL-1.0", "EPL-1.0"}:                     pass,
	LicensePair{"EPL-1.0", "EPL-2.0"}:                     pass,
	LicensePair{"EPL-1.0", "EUPL-1.1"}:                    fail + ", 并入的代码遵循EPL-1.0",
	LicensePair{"EPL-1.0", "EUPL-1.2"}:                    pass,
	LicensePair{"EPL-1.0", "MPL-2.0"}:                     pass,
	LicensePair{"EPL-1.0", "MS-RL"}:                       fail,
	LicensePair{"EPL-1.0", "ODbL-1.0"}:                    fail,
	LicensePair{"EPL-1.0", "OSL-3.0"}:                     fail,
	LicensePair{"EPL-1.0", "Vim"}:                         fail,
	LicensePair{"EPL-1.0", "CDDL-1.0"}:                    pass,
	LicensePair{"EPL-1.0", "CPAL-1.0"}:                    pass,
	LicensePair{"EPL-1.0", "CPL-1.0"}:                     pass,
	LicensePair{"EPL-1.0", "IPL-1.0"}:                     pass,
	LicensePair{"EPL-1.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循EPL-1.0",
	LicensePair{"EPL-1.0", "Nokia"}:                       pass,
	LicensePair{"EPL-1.0", "RPSL-1.0"}:                    fail,
	LicensePair{"EPL-1.0", "SISSL"}:                       pass,
	LicensePair{"EPL-1.0", "Sleepycat"}:                   fail,
	LicensePair{"EPL-1.0", "SPL-1.0"}:                     pass,
	LicensePair{"EPL-1.0", "Apache-2.0"}:                  pass,
	LicensePair{"EPL-1.0", "ECL-2.0"}:                     pass,
	LicensePair{"EPL-1.0", "php-3.01"}:                    pass,
	LicensePair{"EPL-2.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"EPL-2.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"EPL-2.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"EPL-2.0", "GPL-2.0-only"}:                fail,
	LicensePair{"EPL-2.0", "GPL-2.0-or-later"}:            fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"EPL-2.0", "GPL-3.0-only"}:                fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"EPL-2.0", "AGPL-3.0-only"}:               fail,
	LicensePair{"EPL-2.0", "Artistic-2.0"}:                pass,
	LicensePair{"EPL-2.0", "CECILL-2.1"}:                  fail,
	LicensePair{"EPL-2.0", "EPL-1.0"}:                     pass,
	LicensePair{"EPL-2.0", "EPL-2.0"}:                     pass,
	LicensePair{"EPL-2.0", "EUPL-1.1"}:                    fail,
	LicensePair{"EPL-2.0", "EUPL-1.2"}:                    fail,
	LicensePair{"EPL-2.0", "MPL-2.0"}:                     pass,
	LicensePair{"EPL-2.0", "MS-RL"}:                       fail,
	LicensePair{"EPL-2.0", "ODbL-1.0"}:                    fail,
	LicensePair{"EPL-2.0", "OSL-3.0"}:                     fail,
	LicensePair{"EPL-2.0", "Vim"}:                         fail,
	LicensePair{"EPL-2.0", "CDDL-1.0"}:                    pass,
	LicensePair{"EPL-2.0", "CPAL-1.0"}:                    pass,
	LicensePair{"EPL-2.0", "CPL-1.0"}:                     pass,
	LicensePair{"EPL-2.0", "IPL-1.0"}:                     pass,
	LicensePair{"EPL-2.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循EPL-2.0",
	LicensePair{"EPL-2.0", "Nokia"}:                       pass,
	LicensePair{"EPL-2.0", "RPSL-1.0"}:                    fail,
	LicensePair{"EPL-2.0", "SISSL"}:                       pass,
	LicensePair{"EPL-2.0", "Sleepycat"}:                   fail,
	LicensePair{"EPL-2.0", "SPL-1.0"}:                     pass,
	LicensePair{"EPL-2.0", "Apache-2.0"}:                  pass,
	LicensePair{"EPL-2.0", "ECL-2.0"}:                     pass,
	LicensePair{"EPL-2.0", "php-3.01"}:                    pass,
	LicensePair{"EUPL-1.1", "LGPL-2.1-only"}:              pass,
	LicensePair{"EUPL-1.1", "LGPL-2.1-or-later"}:          pass,
	LicensePair{"EUPL-1.1", "LGPL-3.0-only"}:              pass,
	LicensePair{"EUPL-1.1", "GPL-2.0-only"}:               fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"EUPL-1.1", "GPL-2.0-or-later"}:           fail,
	LicensePair{"EUPL-1.1", "GPL-3.0-only"}:               fail,
	LicensePair{"EUPL-1.1", "AGPL-3.0-only"}:              fail,
	LicensePair{"EUPL-1.1", "Artistic-2.0"}:               pass,
	LicensePair{"EUPL-1.1", "CECILL-2.1"}:                 fail + ", 并入的代码遵循EUPL-1.1",
	LicensePair{"EUPL-1.1", "EPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.1", "EPL-2.0"}:                    pass,
	LicensePair{"EUPL-1.1", "EUPL-1.1"}:                   pass,
	LicensePair{"EUPL-1.1", "EUPL-1.2"}:                   pass,
	LicensePair{"EUPL-1.1", "MPL-2.0"}:                    pass,
	LicensePair{"EUPL-1.1", "MS-RL"}:                      fail,
	LicensePair{"EUPL-1.1", "ODbL-1.0"}:                   fail,
	LicensePair{"EUPL-1.1", "OSL-3.0"}:                    fail + ", 组合遵循OSL-3.0",
	LicensePair{"EUPL-1.1", "Vim"}:                        fail,
	LicensePair{"EUPL-1.1", "CDDL-1.0"}:                   pass,
	LicensePair{"EUPL-1.1", "CPAL-1.0"}:                   pass,
	LicensePair{"EUPL-1.1", "CPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.1", "IPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.1", "LPL-1.02"}:                   fail + ", 并入的代码遵循EUPL-1.1",
	LicensePair{"EUPL-1.1", "Nokia"}:                      pass,
	LicensePair{"EUPL-1.1", "RPSL-1.0"}:                   fail,
	LicensePair{"EUPL-1.1", "SISSL"}:                      pass,
	LicensePair{"EUPL-1.1", "Sleepycat"}:                  fail,
	LicensePair{"EUPL-1.1", "SPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.1", "Apache-2.0"}:                 pass,
	LicensePair{"EUPL-1.1", "ECL-2.0"}:                    pass,
	LicensePair{"EUPL-1.1", "php-3.01"}:                   pass,
	LicensePair{"EUPL-1.2", "LGPL-2.1-only"}:              pass,
	LicensePair{"EUPL-1.2", "LGPL-2.1-or-later"}:          pass,
	LicensePair{"EUPL-1.2", "LGPL-3.0-only"}:              pass,
	LicensePair{"EUPL-1.2", "GPL-2.0-only"}:               fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"EUPL-1.2", "GPL-2.0-or-later"}:           fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"EUPL-1.2", "GPL-3.0-only"}:               fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"EUPL-1.2", "AGPL-3.0-only"}:              fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"EUPL-1.2", "Artistic-2.0"}:               pass,
	LicensePair{"EUPL-1.2", "CECILL-2.1"}:                 fail + ", 并入的代码遵循EUPL-1.2",
	LicensePair{"EUPL-1.2", "EPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.2", "EPL-2.0"}:                    pass,
	LicensePair{"EUPL-1.2", "EUPL-1.1"}:                   fail + ", 组合遵循EUPL-1.1",
	LicensePair{"EUPL-1.2", "EUPL-1.2"}:                   pass,
	LicensePair{"EUPL-1.2", "MPL-2.0"}:                    pass,
	LicensePair{"EUPL-1.2", "MS-RL"}:                      fail,
	LicensePair{"EUPL-1.2", "ODbL-1.0"}:                   fail,
	LicensePair{"EUPL-1.2", "OSL-3.0"}:                    fail + ", 组合遵循OSL-3.0",
	LicensePair{"EUPL-1.2", "Vim"}:                        fail,
	LicensePair{"EUPL-1.2", "CDDL-1.0"}:                   pass,
	LicensePair{"EUPL-1.2", "CPAL-1.0"}:                   pass,
	LicensePair{"EUPL-1.2", "CPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.2", "IPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.2", "LPL-1.02"}:                   fail + ", 并入的代码遵循EUPL-1.2",
	LicensePair{"EUPL-1.2", "Nokia"}:                      pass,
	LicensePair{"EUPL-1.2", "RPSL-1.0"}:                   fail,
	LicensePair{"EUPL-1.2", "SISSL"}:                      pass,
	LicensePair{"EUPL-1.2", "Sleepycat"}:                  fail,
	LicensePair{"EUPL-1.2", "SPL-1.0"}:                    pass,
	LicensePair{"EUPL-1.2", "Apache-2.0"}:                 pass,
	LicensePair{"EUPL-1.2", "ECL-2.0"}:                    pass,
	LicensePair{"EUPL-1.2", "php-3.01"}:                   pass,
	LicensePair{"MPL-2.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"MPL-2.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"MPL-2.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"MPL-2.0", "GPL-2.0-only"}:                fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"MPL-2.0", "GPL-2.0-or-later"}:            fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"MPL-2.0", "GPL-3.0-only"}:                fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"MPL-2.0", "AGPL-3.0-only"}:               fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"MPL-2.0", "Artistic-2.0"}:                pass,
	LicensePair{"MPL-2.0", "CECILL-2.1"}:                  fail,
	LicensePair{"MPL-2.0", "EPL-1.0"}:                     pass,
	LicensePair{"MPL-2.0", "EPL-2.0"}:                     pass,
	LicensePair{"MPL-2.0", "EUPL-1.1"}:                    fail,
	LicensePair{"MPL-2.0", "EUPL-1.2"}:                    fail + ", 并入的代码遵循MPL-2.0",
	LicensePair{"MPL-2.0", "MPL-2.0"}:                     pass,
	LicensePair{"MPL-2.0", "MS-RL"}:                       fail,
	LicensePair{"MPL-2.0", "ODbL-1.0"}:                    fail,
	LicensePair{"MPL-2.0", "OSL-3.0"}:                     fail,
	LicensePair{"MPL-2.0", "Vim"}:                         fail,
	LicensePair{"MPL-2.0", "CDDL-1.0"}:                    pass,
	LicensePair{"MPL-2.0", "CPAL-1.0"}:                    pass,
	LicensePair{"MPL-2.0", "CPL-1.0"}:                     pass,
	LicensePair{"MPL-2.0", "IPL-1.0"}:                     pass,
	LicensePair{"MPL-2.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循MPL-2.0",
	LicensePair{"MPL-2.0", "Nokia"}:                       pass,
	LicensePair{"MPL-2.0", "RPSL-1.0"}:                    fail + ", 并入的代码遵循MPL-2.0",
	LicensePair{"MPL-2.0", "SISSL"}:                       pass,
	LicensePair{"MPL-2.0", "Sleepycat"}:                   fail,
	LicensePair{"MPL-2.0", "SPL-1.0"}:                     pass,
	LicensePair{"MPL-2.0", "Apache-2.0"}:                  pass,
	LicensePair{"MPL-2.0", "ECL-2.0"}:                     pass,
	LicensePair{"MPL-2.0", "php-3.01"}:                    pass,
	LicensePair{"MS-RL", "LGPL-2.1-only"}:                 pass,
	LicensePair{"MS-RL", "LGPL-2.1-or-later"}:             pass,
	LicensePair{"MS-RL", "LGPL-3.0-only"}:                 pass,
	LicensePair{"MS-RL", "GPL-2.0-only"}:                  fail,
	LicensePair{"MS-RL", "GPL-2.0-or-later"}:              fail,
	LicensePair{"MS-RL", "GPL-3.0-only"}:                  fail,
	LicensePair{"MS-RL", "AGPL-3.0-only"}:                 fail,
	LicensePair{"MS-RL", "Artistic-2.0"}:                  pass,
	LicensePair{"MS-RL", "CECILL-2.1"}:                    fail,
	LicensePair{"MS-RL", "EPL-1.0"}:                       pass,
	LicensePair{"MS-RL", "EPL-2.0"}:                       pass,
	LicensePair{"MS-RL", "EUPL-1.1"}:                      fail,
	LicensePair{"MS-RL", "EUPL-1.2"}:                      fail,
	LicensePair{"MS-RL", "MPL-2.0"}:                       pass,
	LicensePair{"MS-RL", "MS-RL"}:                         pass,
	LicensePair{"MS-RL", "ODbL-1.0"}:                      fail,
	LicensePair{"MS-RL", "OSL-3.0"}:                       fail,
	LicensePair{"MS-RL", "Vim"}:                           fail,
	LicensePair{"MS-RL", "CDDL-1.0"}:                      pass,
	LicensePair{"MS-RL", "CPAL-1.0"}:                      pass,
	LicensePair{"MS-RL", "CPL-1.0"}:                       pass,
	LicensePair{"MS-RL", "IPL-1.0"}:                       pass,
	LicensePair{"MS-RL", "LPL-1.02"}:                      fail + ", 并入的代码遵循MS-RL",
	LicensePair{"MS-RL", "Nokia"}:                         pass,
	LicensePair{"MS-RL", "RPSL-1.0"}:                      fail,
	LicensePair{"MS-RL", "SISSL"}:                         pass,
	LicensePair{"MS-RL", "Sleepycat"}:                     fail,
	LicensePair{"MS-RL", "SPL-1.0"}:                       pass,
	LicensePair{"MS-RL", "Apache-2.0"}:                    pass,
	LicensePair{"MS-RL", "ECL-2.0"}:                       pass,
	LicensePair{"MS-RL", "php-3.01"}:                      pass,
	LicensePair{"OSL-3.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"OSL-3.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"OSL-3.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"OSL-3.0", "GPL-2.0-only"}:                fail,
	LicensePair{"OSL-3.0", "GPL-2.0-or-later"}:            fail,
	LicensePair{"OSL-3.0", "GPL-3.0-only"}:                fail,
	LicensePair{"OSL-3.0", "AGPL-3.0-only"}:               fail,
	LicensePair{"OSL-3.0", "Artistic-2.0"}:                pass,
	LicensePair{"OSL-3.0", "CECILL-2.1"}:                  fail,
	LicensePair{"OSL-3.0", "EPL-1.0"}:                     pass,
	LicensePair{"OSL-3.0", "EPL-2.0"}:                     pass,
	LicensePair{"OSL-3.0", "EUPL-1.1"}:                    fail + ", 并入的代码遵循OSL-3.0",
	LicensePair{"OSL-3.0", "EUPL-1.2"}:                    fail + ", 并入的代码遵循OSL-3.0",
	LicensePair{"OSL-3.0", "MPL-2.0"}:                     pass,
	LicensePair{"OSL-3.0", "MS-RL"}:                       fail,
	LicensePair{"OSL-3.0", "ODbL-1.0"}:                    fail,
	LicensePair{"OSL-3.0", "OSL-3.0"}:                     pass,
	LicensePair{"OSL-3.0", "Vim"}:                         fail,
	LicensePair{"OSL-3.0", "CDDL-1.0"}:                    pass,
	LicensePair{"OSL-3.0", "CPAL-1.0"}:                    pass,
	LicensePair{"OSL-3.0", "CPL-1.0"}:                     pass,
	LicensePair{"OSL-3.0", "IPL-1.0"}:                     pass,
	LicensePair{"OSL-3.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循OSL-3.0",
	LicensePair{"OSL-3.0", "Nokia"}:                       pass,
	LicensePair{"OSL-3.0", "RPSL-1.0"}:                    fail,
	LicensePair{"OSL-3.0", "SISSL"}:                       pass,
	LicensePair{"OSL-3.0", "Sleepycat"}:                   fail,
	LicensePair{"OSL-3.0", "SPL-1.0"}:                     pass,
	LicensePair{"OSL-3.0", "Apache-2.0"}:                  pass,
	LicensePair{"OSL-3.0", "ECL-2.0"}:                     pass,
	LicensePair{"OSL-3.0", "php-3.01"}:                    pass,
	LicensePair{"Vim", "LGPL-2.1-only"}:                   pass,
	LicensePair{"Vim", "LGPL-2.1-or-later"}:               pass,
	LicensePair{"Vim", "LGPL-3.0-only"}:                   pass,
	LicensePair{"Vim", "GPL-2.0-only"}:                    fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"Vim", "GPL-2.0-or-later"}:                fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"Vim", "GPL-3.0-only"}:                    fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"Vim", "AGPL-3.0-only"}:                   fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"Vim", "Artistic-2.0"}:                    pass,
	LicensePair{"Vim", "CECILL-2.1"}:                      fail,
	LicensePair{"Vim", "EPL-1.0"}:                         pass,
	LicensePair{"Vim", "EPL-2.0"}:                         pass,
	LicensePair{"Vim", "EUPL-1.1"}:                        fail,
	LicensePair{"Vim", "EUPL-1.2"}:                        fail,
	LicensePair{"Vim", "MPL-2.0"}:                         pass,
	LicensePair{"Vim", "MS-RL"}:                           fail,
	LicensePair{"Vim", "ODbL-1.0"}:                        fail,
	LicensePair{"Vim", "OSL-3.0"}:                         fail,
	LicensePair{"Vim", "Vim"}:                             pass,
	LicensePair{"Vim", "CDDL-1.0"}:                        pass,
	LicensePair{"Vim", "CPAL-1.0"}:                        pass,
	LicensePair{"Vim", "CPL-1.0"}:                         pass,
	LicensePair{"Vim", "IPL-1.0"}:                         pass,
	LicensePair{"Vim", "LPL-1.02"}:                        fail + ", 并入的代码遵循Vim",
	LicensePair{"Vim", "Nokia"}:                           pass,
	LicensePair{"Vim", "RPSL-1.0"}:                        fail,
	LicensePair{"Vim", "SISSL"}:                           pass,
	LicensePair{"Vim", "Sleepycat"}:                       fail,
	LicensePair{"Vim", "SPL-1.0"}:                         pass,
	LicensePair{"Vim", "Apache-2.0"}:                      pass,
	LicensePair{"Vim", "ECL-2.0"}:                         pass,
	LicensePair{"Vim", "php-3.01"}:                        pass,
	LicensePair{"CDDL-1.0", "LGPL-2.1-only"}:              pass,
	LicensePair{"CDDL-1.0", "LGPL-2.1-or-later"}:          pass,
	LicensePair{"CDDL-1.0", "LGPL-3.0-only"}:              pass,
	LicensePair{"CDDL-1.0", "GPL-2.0-only"}:               fail,
	LicensePair{"CDDL-1.0", "GPL-2.0-or-later"}:           fail,
	LicensePair{"CDDL-1.0", "GPL-3.0-only"}:               fail,
	LicensePair{"CDDL-1.0", "AGPL-3.0-only"}:              fail,
	LicensePair{"CDDL-1.0", "Artistic-2.0"}:               pass,
	LicensePair{"CDDL-1.0", "CECILL-2.1"}:                 fail,
	LicensePair{"CDDL-1.0", "EPL-1.0"}:                    pass,
	LicensePair{"CDDL-1.0", "EPL-2.0"}:                    pass,
	LicensePair{"CDDL-1.0", "EUPL-1.1"}:                   fail,
	LicensePair{"CDDL-1.0", "EUPL-1.2"}:                   fail,
	LicensePair{"CDDL-1.0", "MPL-2.0"}:                    pass,
	LicensePair{"CDDL-1.0", "MS-RL"}:                      fail,
	LicensePair{"CDDL-1.0", "ODbL-1.0"}:                   fail,
	LicensePair{"CDDL-1.0", "OSL-3.0"}:                    fail,
	LicensePair{"CDDL-1.0", "Vim"}:                        fail,
	LicensePair{"CDDL-1.0", "CDDL-1.0"}:                   pass,
	LicensePair{"CDDL-1.0", "CPAL-1.0"}:                   pass,
	LicensePair{"CDDL-1.0", "CPL-1.0"}:                    pass,
	LicensePair{"CDDL-1.0", "IPL-1.0"}:                    pass,
	LicensePair{"CDDL-1.0", "LPL-1.02"}:                   fail + ", 并入的代码遵循CDDL-1.0",
	LicensePair{"CDDL-1.0", "Nokia"}:                      pass,
	LicensePair{"CDDL-1.0", "RPSL-1.0"}:                   fail,
	LicensePair{"CDDL-1.0", "SISSL"}:                      pass,
	LicensePair{"CDDL-1.0", "Sleepycat"}:                  fail,
	LicensePair{"CDDL-1.0", "SPL-1.0"}:                    pass,
	LicensePair{"CDDL-1.0", "Apache-2.0"}:                 pass,
	LicensePair{"CDDL-1.0", "ECL-2.0"}:                    pass,
	LicensePair{"CDDL-1.0", "php-3.01"}:                   pass,
	LicensePair{"CPAL-1.0", "LGPL-2.1-only"}:              pass,
	LicensePair{"CPAL-1.0", "LGPL-2.1-or-later"}:          pass,
	LicensePair{"CPAL-1.0", "LGPL-3.0-only"}:              pass,
	LicensePair{"CPAL-1.0", "GPL-2.0-only"}:               fail,
	LicensePair{"CPAL-1.0", "GPL-2.0-or-later"}:           fail,
	LicensePair{"CPAL-1.0", "GPL-3.0-only"}:               fail,
	LicensePair{"CPAL-1.0", "AGPL-3.0-only"}:              fail,
	LicensePair{"CPAL-1.0", "Artistic-2.0"}:               pass,
	LicensePair{"CPAL-1.0", "CECILL-2.1"}:                 fail,
	LicensePair{"CPAL-1.0", "EPL-1.0"}:                    pass,
	LicensePair{"CPAL-1.0", "EPL-2.0"}:                    pass,
	LicensePair{"CPAL-1.0", "EUPL-1.1"}:                   fail,
	LicensePair{"CPAL-1.0", "EUPL-1.2"}:                   fail,
	LicensePair{"CPAL-1.0", "MPL-2.0"}:                    pass,
	LicensePair{"CPAL-1.0", "MS-RL"}:                      fail,
	LicensePair{"CPAL-1.0", "ODbL-1.0"}:                   fail,
	LicensePair{"CPAL-1.0", "OSL-3.0"}:                    fail,
	LicensePair{"CPAL-1.0", "Vim"}:                        fail,
	LicensePair{"CPAL-1.0", "CDDL-1.0"}:                   pass,
	LicensePair{"CPAL-1.0", "CPAL-1.0"}:                   pass,
	LicensePair{"CPAL-1.0", "CPL-1.0"}:                    pass,
	LicensePair{"CPAL-1.0", "IPL-1.0"}:                    pass,
	LicensePair{"CPAL-1.0", "LPL-1.02"}:                   fail + ", 并入的代码遵循CPAL-1.0",
	LicensePair{"CPAL-1.0", "Nokia"}:                      pass,
	LicensePair{"CPAL-1.0", "RPSL-1.0"}:                   fail,
	LicensePair{"CPAL-1.0", "SISSL"}:                      pass,
	LicensePair{"CPAL-1.0", "Sleepycat"}:                  fail,
	LicensePair{"CPAL-1.0", "SPL-1.0"}:                    pass,
	LicensePair{"CPAL-1.0", "Apache-2.0"}:                 pass,
	LicensePair{"CPAL-1.0", "ECL-2.0"}:                    pass,
	LicensePair{"CPAL-1.0", "php-3.01"}:                   pass,
	LicensePair{"CPL-1.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"CPL-1.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"CPL-1.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"CPL-1.0", "GPL-2.0-only"}:                fail,
	LicensePair{"CPL-1.0", "GPL-2.0-or-later"}:            fail,
	LicensePair{"CPL-1.0", "GPL-3.0-only"}:                fail,
	LicensePair{"CPL-1.0", "AGPL-3.0-only"}:               fail,
	LicensePair{"CPL-1.0", "Artistic-2.0"}:                pass,
	LicensePair{"CPL-1.0", "CECILL-2.1"}:                  fail,
	LicensePair{"CPL-1.0", "EPL-1.0"}:                     pass,
	LicensePair{"CPL-1.0", "EPL-2.0"}:                     pass,
	LicensePair{"CPL-1.0", "EUPL-1.1"}:                    pass,
	LicensePair{"CPL-1.0", "EUPL-1.2"}:                    fail,
	LicensePair{"CPL-1.0", "MPL-2.0"}:                     pass,
	LicensePair{"CPL-1.0", "MS-RL"}:                       fail,
	LicensePair{"CPL-1.0", "ODbL-1.0"}:                    fail,
	LicensePair{"CPL-1.0", "OSL-3.0"}:                     fail,
	LicensePair{"CPL-1.0", "Vim"}:                         fail,
	LicensePair{"CPL-1.0", "CDDL-1.0"}:                    pass,
	LicensePair{"CPL-1.0", "CPAL-1.0"}:                    pass,
	LicensePair{"CPL-1.0", "CPL-1.0"}:                     pass,
	LicensePair{"CPL-1.0", "IPL-1.0"}:                     pass,
	LicensePair{"CPL-1.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循CPL-1.0",
	LicensePair{"CPL-1.0", "Nokia"}:                       pass,
	LicensePair{"CPL-1.0", "RPSL-1.0"}:                    fail + ", 并入的代码遵循CPL-1.0",
	LicensePair{"CPL-1.0", "SISSL"}:                       pass,
	LicensePair{"CPL-1.0", "Sleepycat"}:                   fail,
	LicensePair{"CPL-1.0", "SPL-1.0"}:                     pass,
	LicensePair{"CPL-1.0", "Apache-2.0"}:                  pass,
	LicensePair{"CPL-1.0", "ECL-2.0"}:                     pass,
	LicensePair{"CPL-1.0", "php-3.01"}:                    pass,
	LicensePair{"IPL-1.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"IPL-1.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"IPL-1.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"IPL-1.0", "GPL-2.0-only"}:                fail,
	LicensePair{"IPL-1.0", "GPL-2.0-or-later"}:            fail,
	LicensePair{"IPL-1.0", "GPL-3.0-only"}:                fail,
	LicensePair{"IPL-1.0", "AGPL-3.0-only"}:               fail,
	LicensePair{"IPL-1.0", "Artistic-2.0"}:                pass,
	LicensePair{"IPL-1.0", "CECILL-2.1"}:                  fail,
	LicensePair{"IPL-1.0", "EPL-1.0"}:                     pass,
	LicensePair{"IPL-1.0", "EPL-2.0"}:                     pass,
	LicensePair{"IPL-1.0", "EUPL-1.1"}:                    fail,
	LicensePair{"IPL-1.0", "EUPL-1.2"}:                    fail,
	LicensePair{"IPL-1.0", "MPL-2.0"}:                     pass,
	LicensePair{"IPL-1.0", "MS-RL"}:                       fail,
	LicensePair{"IPL-1.0", "ODbL-1.0"}:                    fail,
	LicensePair{"IPL-1.0", "OSL-3.0"}:                     fail,
	LicensePair{"IPL-1.0", "Vim"}:                         fail,
	LicensePair{"IPL-1.0", "CDDL-1.0"}:                    pass,
	LicensePair{"IPL-1.0", "CPAL-1.0"}:                    pass,
	LicensePair{"IPL-1.0", "CPL-1.0"}:                     pass,
	LicensePair{"IPL-1.0", "IPL-1.0"}:                     pass,
	LicensePair{"IPL-1.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循IPL-1.0",
	LicensePair{"IPL-1.0", "Nokia"}:                       pass,
	LicensePair{"IPL-1.0", "RPSL-1.0"}:                    fail + ", 并入的代码遵循IPL-1.0",
	LicensePair{"IPL-1.0", "SISSL"}:                       pass,
	LicensePair{"IPL-1.0", "Sleepycat"}:                   fail,
	LicensePair{"IPL-1.0", "SPL-1.0"}:                     pass,
	LicensePair{"IPL-1.0", "Apache-2.0"}:                  pass,
	LicensePair{"IPL-1.0", "ECL-2.0"}:                     pass,
	LicensePair{"IPL-1.0", "php-3.01"}:                    pass,
	LicensePair{"LPL-1.02", "LGPL-2.1-only"}:              pass,
	LicensePair{"LPL-1.02", "LGPL-2.1-or-later"}:          pass,
	LicensePair{"LPL-1.02", "LGPL-3.0-only"}:              pass,
	LicensePair{"LPL-1.02", "GPL-2.0-only"}:               fail,
	LicensePair{"LPL-1.02", "GPL-2.0-or-later"}:           fail,
	LicensePair{"LPL-1.02", "GPL-3.0-only"}:               fail,
	LicensePair{"LPL-1.02", "AGPL-3.0-only"}:              fail,
	LicensePair{"LPL-1.02", "Artistic-2.0"}:               pass,
	LicensePair{"LPL-1.02", "CECILL-2.1"}:                 fail + ", 组合遵循CECILL-2.1",
	LicensePair{"LPL-1.02", "EPL-1.0"}:                    pass,
	LicensePair{"LPL-1.02", "EPL-2.0"}:                    pass,
	LicensePair{"LPL-1.02", "EUPL-1.1"}:                   fail + ", 组合遵循EUPL-1.1",
	LicensePair{"LPL-1.02", "EUPL-1.2"}:                   fail + ", 组合遵循EUPL-1.2",
	LicensePair{"LPL-1.02", "MPL-2.0"}:                    pass,
	LicensePair{"LPL-1.02", "MS-RL"}:                      fail + ", 组合遵循MS-RL",
	LicensePair{"LPL-1.02", "ODbL-1.0"}:                   fail + ", 组合遵循ODbL-1.0",
	LicensePair{"LPL-1.02", "OSL-3.0"}:                    fail + ", 组合遵循OSL-3.0",
	LicensePair{"LPL-1.02", "Vim"}:                        fail + ", 组合遵循Vim",
	LicensePair{"LPL-1.02", "CDDL-1.0"}:                   pass,
	LicensePair{"LPL-1.02", "CPAL-1.0"}:                   pass,
	LicensePair{"LPL-1.02", "CPL-1.0"}:                    pass,
	LicensePair{"LPL-1.02", "IPL-1.0"}:                    pass,
	LicensePair{"LPL-1.02", "LPL-1.02"}:                   pass,
	LicensePair{"LPL-1.02", "Nokia"}:                      pass,
	LicensePair{"LPL-1.02", "RPSL-1.0"}:                   fail,
	LicensePair{"LPL-1.02", "SISSL"}:                      pass,
	LicensePair{"LPL-1.02", "Sleepycat"}:                  fail + ", 组合遵循Sleepycat",
	LicensePair{"LPL-1.02", "SPL-1.0"}:                    pass,
	LicensePair{"LPL-1.02", "Apache-2.0"}:                 pass,
	LicensePair{"LPL-1.02", "ECL-2.0"}:                    pass,
	LicensePair{"LPL-1.02", "php-3.01"}:                   pass,
	LicensePair{"Nokia", "LGPL-2.1-only"}:                 pass,
	LicensePair{"Nokia", "LGPL-2.1-or-later"}:             pass,
	LicensePair{"Nokia", "LGPL-3.0-only"}:                 pass,
	LicensePair{"Nokia", "GPL-2.0-only"}:                  fail,
	LicensePair{"Nokia", "GPL-2.0-or-later"}:              fail,
	LicensePair{"Nokia", "GPL-3.0-only"}:                  fail,
	LicensePair{"Nokia", "AGPL-3.0-only"}:                 fail,
	LicensePair{"Nokia", "Artistic-2.0"}:                  pass,
	LicensePair{"Nokia", "CECILL-2.1"}:                    fail,
	LicensePair{"Nokia", "EPL-1.0"}:                       pass,
	LicensePair{"Nokia", "EPL-2.0"}:                       pass,
	LicensePair{"Nokia", "EUPL-1.1"}:                      fail,
	LicensePair{"Nokia", "EUPL-1.2"}:                      fail,
	LicensePair{"Nokia", "MPL-2.0"}:                       pass,
	LicensePair{"Nokia", "MS-RL"}:                         fail,
	LicensePair{"Nokia", "ODbL-1.0"}:                      fail,
	LicensePair{"Nokia", "OSL-3.0"}:                       fail,
	LicensePair{"Nokia", "Vim"}:                           fail,
	LicensePair{"Nokia", "CDDL-1.0"}:                      pass,
	LicensePair{"Nokia", "CPAL-1.0"}:                      pass,
	LicensePair{"Nokia", "CPL-1.0"}:                       pass,
	LicensePair{"Nokia", "IPL-1.0"}:                       pass,
	LicensePair{"Nokia", "LPL-1.02"}:                      fail + ", 并入的代码遵循Nokia",
	LicensePair{"Nokia", "Nokia"}:                         pass,
	LicensePair{"Nokia", "RPSL-1.0"}:                      fail,
	LicensePair{"Nokia", "SISSL"}:                         pass,
	LicensePair{"Nokia", "Sleepycat"}:                     fail,
	LicensePair{"Nokia", "SPL-1.0"}:                       pass,
	LicensePair{"Nokia", "Apache-2.0"}:                    pass,
	LicensePair{"Nokia", "ECL-2.0"}:                       pass,
	LicensePair{"Nokia", "php-3.01"}:                      pass,
	LicensePair{"RPSL-1.0", "LGPL-2.1-only"}:              pass,
	LicensePair{"RPSL-1.0", "LGPL-2.1-or-later"}:          pass,
	LicensePair{"RPSL-1.0", "LGPL-3.0-only"}:              pass,
	LicensePair{"RPSL-1.0", "GPL-2.0-only"}:               fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"RPSL-1.0", "GPL-2.0-or-later"}:           fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"RPSL-1.0", "GPL-3.0-only"}:               fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"RPSL-1.0", "AGPL-3.0-only"}:              fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"RPSL-1.0", "Artistic-2.0"}:               pass,
	LicensePair{"RPSL-1.0", "CECILL-2.1"}:                 fail,
	LicensePair{"RPSL-1.0", "EPL-1.0"}:                    pass,
	LicensePair{"RPSL-1.0", "EPL-2.0"}:                    pass,
	LicensePair{"RPSL-1.0", "EUPL-1.1"}:                   fail,
	LicensePair{"RPSL-1.0", "EUPL-1.2"}:                   fail,
	LicensePair{"RPSL-1.0", "MPL-2.0"}:                    pass,
	LicensePair{"RPSL-1.0", "MS-RL"}:                      fail,
	LicensePair{"RPSL-1.0", "ODbL-1.0"}:                   fail,
	LicensePair{"RPSL-1.0", "OSL-3.0"}:                    fail,
	LicensePair{"RPSL-1.0", "Vim"}:                        fail,
	LicensePair{"RPSL-1.0", "CDDL-1.0"}:                   pass,
	LicensePair{"RPSL-1.0", "CPAL-1.0"}:                   pass,
	LicensePair{"RPSL-1.0", "CPL-1.0"}:                    pass,
	LicensePair{"RPSL-1.0", "IPL-1.0"}:                    pass,
	LicensePair{"RPSL-1.0", "LPL-1.02"}:                   fail + ", 并入的代码遵循RPSL-1.0",
	LicensePair{"RPSL-1.0", "Nokia"}:                      pass,
	LicensePair{"RPSL-1.0", "RPSL-1.0"}:                   pass,
	LicensePair{"RPSL-1.0", "SISSL"}:                      pass,
	LicensePair{"RPSL-1.0", "Sleepycat"}:                  fail,
	LicensePair{"RPSL-1.0", "SPL-1.0"}:                    pass,
	LicensePair{"RPSL-1.0", "Apache-2.0"}:                 pass,
	LicensePair{"RPSL-1.0", "ECL-2.0"}:                    pass,
	LicensePair{"RPSL-1.0", "php-3.01"}:                   pass,
	LicensePair{"SISSL", "LGPL-2.1-only"}:                 pass,
	LicensePair{"SISSL", "LGPL-2.1-or-later"}:             pass,
	LicensePair{"SISSL", "LGPL-3.0-only"}:                 pass,
	LicensePair{"SISSL", "GPL-2.0-only"}:                  fail,
	LicensePair{"SISSL", "GPL-2.0-or-later"}:              fail,
	LicensePair{"SISSL", "GPL-3.0-only"}:                  fail,
	LicensePair{"SISSL", "AGPL-3.0-only"}:                 fail,
	LicensePair{"SISSL", "Artistic-2.0"}:                  pass,
	LicensePair{"SISSL", "CECILL-2.1"}:                    fail,
	LicensePair{"SISSL", "EPL-1.0"}:                       pass,
	LicensePair{"SISSL", "EPL-2.0"}:                       pass,
	LicensePair{"SISSL", "EUPL-1.1"}:                      fail,
	LicensePair{"SISSL", "EUPL-1.2"}:                      fail,
	LicensePair{"SISSL", "MPL-2.0"}:                       pass,
	LicensePair{"SISSL", "MS-RL"}:                         fail,
	LicensePair{"SISSL", "ODbL-1.0"}:                      fail,
	LicensePair{"SISSL", "OSL-3.0"}:                       fail,
	LicensePair{"SISSL", "Vim"}:                           fail,
	LicensePair{"SISSL", "CDDL-1.0"}:                      pass,
	LicensePair{"SISSL", "CPAL-1.0"}:                      pass,
	LicensePair{"SISSL", "CPL-1.0"}:                       pass,
	LicensePair{"SISSL", "IPL-1.0"}:                       pass,
	LicensePair{"SISSL", "LPL-1.02"}:                      fail + ", 并入的代码遵循SISSL",
	LicensePair{"SISSL", "Nokia"}:                         pass,
	LicensePair{"SISSL", "RPSL-1.0"}:                      fail,
	LicensePair{"SISSL", "SISSL"}:                         pass,
	LicensePair{"SISSL", "Sleepycat"}:                     fail,
	LicensePair{"SISSL", "SPL-1.0"}:                       pass,
	LicensePair{"SISSL", "Apache-2.0"}:                    pass,
	LicensePair{"SISSL", "ECL-2.0"}:                       pass,
	LicensePair{"SISSL", "php-3.01"}:                      pass,
	LicensePair{"Sleepycat", "LGPL-2.1-only"}:             pass,
	LicensePair{"Sleepycat", "LGPL-2.1-or-later"}:         pass,
	LicensePair{"Sleepycat", "LGPL-3.0-only"}:             pass,
	LicensePair{"Sleepycat", "GPL-2.0-only"}:              fail + ", 组合遵循GPL-2.0-only",
	LicensePair{"Sleepycat", "GPL-2.0-or-later"}:          fail + ", 组合遵循GPL-2.0-or-later",
	LicensePair{"Sleepycat", "GPL-3.0-only"}:              fail + ", 组合遵循GPL-3.0-only",
	LicensePair{"Sleepycat", "AGPL-3.0-only"}:             fail + ", 组合遵循AGPL-3.0-only",
	LicensePair{"Sleepycat", "Artistic-2.0"}:              pass,
	LicensePair{"Sleepycat", "CECILL-2.1"}:                fail,
	LicensePair{"Sleepycat", "EPL-1.0"}:                   pass,
	LicensePair{"Sleepycat", "EPL-2.0"}:                   pass,
	LicensePair{"Sleepycat", "EUPL-1.1"}:                  fail,
	LicensePair{"Sleepycat", "EUPL-1.2"}:                  fail,
	LicensePair{"Sleepycat", "MPL-2.0"}:                   pass,
	LicensePair{"Sleepycat", "MS-RL"}:                     fail,
	LicensePair{"Sleepycat", "ODbL-1.0"}:                  fail,
	LicensePair{"Sleepycat", "OSL-3.0"}:                   fail,
	LicensePair{"Sleepycat", "Vim"}:                       fail,
	LicensePair{"Sleepycat", "CDDL-1.0"}:                  pass,
	LicensePair{"Sleepycat", "CPAL-1.0"}:                  pass,
	LicensePair{"Sleepycat", "CPL-1.0"}:                   pass,
	LicensePair{"Sleepycat", "IPL-1.0"}:                   pass,
	LicensePair{"Sleepycat", "LPL-1.02"}:                  fail + ", 并入的代码遵循Sleepycat",
	LicensePair{"Sleepycat", "Nokia"}:                     pass,
	LicensePair{"Sleepycat", "RPSL-1.0"}:                  fail,
	LicensePair{"Sleepycat", "SISSL"}:                     pass,
	LicensePair{"Sleepycat", "Sleepycat"}:                 pass,
	LicensePair{"Sleepycat", "SPL-1.0"}:                   pass,
	LicensePair{"Sleepycat", "Apache-2.0"}:                pass,
	LicensePair{"Sleepycat", "ECL-2.0"}:                   pass,
	LicensePair{"Sleepycat", "php-3.01"}:                  pass,
	LicensePair{"SPL-1.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"SPL-1.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"SPL-1.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"SPL-1.0", "GPL-2.0-only"}:                fail,
	LicensePair{"SPL-1.0", "GPL-2.0-or-later"}:            fail,
	LicensePair{"SPL-1.0", "GPL-3.0-only"}:                fail,
	LicensePair{"SPL-1.0", "AGPL-3.0-only"}:               fail,
	LicensePair{"SPL-1.0", "Artistic-2.0"}:                pass,
	LicensePair{"SPL-1.0", "CECILL-2.1"}:                  fail,
	LicensePair{"SPL-1.0", "EPL-1.0"}:                     pass,
	LicensePair{"SPL-1.0", "EPL-2.0"}:                     pass,
	LicensePair{"SPL-1.0", "EUPL-1.1"}:                    fail,
	LicensePair{"SPL-1.0", "EUPL-1.2"}:                    fail,
	LicensePair{"SPL-1.0", "MPL-2.0"}:                     pass,
	LicensePair{"SPL-1.0", "MS-RL"}:                       fail,
	LicensePair{"SPL-1.0", "ODbL-1.0"}:                    fail,
	LicensePair{"SPL-1.0", "OSL-3.0"}:                     fail,
	LicensePair{"SPL-1.0", "Vim"}:                         fail,
	LicensePair{"SPL-1.0", "CDDL-1.0"}:                    pass,
	LicensePair{"SPL-1.0", "CPAL-1.0"}:                    pass,
	LicensePair{"SPL-1.0", "CPL-1.0"}:                     pass,
	LicensePair{"SPL-1.0", "IPL-1.0"}:                     pass,
	LicensePair{"SPL-1.0", "LPL-1.02"}:                    fail + ", 并入的代码遵循SISSL",
	LicensePair{"SPL-1.0", "Nokia"}:                       pass,
	LicensePair{"SPL-1.0", "RPSL-1.0"}:                    fail,
	LicensePair{"SPL-1.0", "SISSL"}:                       pass,
	LicensePair{"SPL-1.0", "Sleepycat"}:                   fail,
	LicensePair{"SPL-1.0", "SPL-1.0"}:                     pass,
	LicensePair{"SPL-1.0", "Apache-2.0"}:                  pass,
	LicensePair{"SPL-1.0", "ECL-2.0"}:                     pass,
	LicensePair{"SPL-1.0", "php-3.01"}:                    pass,
	LicensePair{"php-3.01", "LGPL-2.1-only"}:              fail,
	LicensePair{"php-3.01", "LGPL-2.1-or-later"}:          fail,
	LicensePair{"php-3.01", "LGPL-3.0-only"}:              fail,
	LicensePair{"php-3.01", "GPL-2.0-only"}:               fail,
	LicensePair{"php-3.01", "GPL-2.0-or-later"}:           fail,
	LicensePair{"php-3.01", "GPL-3.0-only"}:               fail,
	LicensePair{"php-3.01", "AGPL-3.0-only"}:              fail,
	LicensePair{"php-3.01", "Artistic-2.0"}:               pass,
	LicensePair{"php-3.01", "CECILL-2.1"}:                 pass,
	LicensePair{"php-3.01", "EPL-1.0"}:                    pass,
	LicensePair{"php-3.01", "EPL-2.0"}:                    pass,
	LicensePair{"php-3.01", "EUPL-1.1"}:                   pass,
	LicensePair{"php-3.01", "EUPL-1.2"}:                   pass,
	LicensePair{"php-3.01", "MPL-2.0"}:                    pass,
	LicensePair{"php-3.01", "MS-RL"}:                      pass,
	LicensePair{"php-3.01", "ODbL-1.0"}:                   pass,
	LicensePair{"php-3.01", "OSL-3.0"}:                    pass,
	LicensePair{"php-3.01", "Vim"}:                        pass,
	LicensePair{"php-3.01", "CDDL-1.0"}:                   pass,
	LicensePair{"php-3.01", "CPAL-1.0"}:                   pass,
	LicensePair{"php-3.01", "CPL-1.0"}:                    pass,
	LicensePair{"php-3.01", "IPL-1.0"}:                    pass,
	LicensePair{"php-3.01", "LPL-1.02"}:                   pass,
	LicensePair{"php-3.01", "Nokia"}:                      pass,
	LicensePair{"php-3.01", "RPSL-1.0"}:                   pass,
	LicensePair{"php-3.01", "SISSL"}:                      pass,
	LicensePair{"php-3.01", "Sleepycat"}:                  pass,
	LicensePair{"php-3.01", "SPL-1.0"}:                    pass,
	LicensePair{"php-3.01", "Apache-2.0"}:                 pass,
	LicensePair{"php-3.01", "ECL-2.0"}:                    pass,
	LicensePair{"php-3.01", "php-3.01"}:                   pass,
	LicensePair{"Apache-2.0", "LGPL-2.1-only"}:            pass,
	LicensePair{"Apache-2.0", "LGPL-2.1-or-later"}:        pass,
	LicensePair{"Apache-2.0", "LGPL-3.0-only"}:            pass,
	LicensePair{"Apache-2.0", "GPL-2.0-only"}:             fail,
	LicensePair{"Apache-2.0", "GPL-2.0-or-later"}:         pass,
	LicensePair{"Apache-2.0", "GPL-3.0-only"}:             pass,
	LicensePair{"Apache-2.0", "AGPL-3.0-only"}:            pass,
	LicensePair{"Apache-2.0", "Artistic-2.0"}:             pass,
	LicensePair{"Apache-2.0", "CECILL-2.1"}:               pass,
	LicensePair{"Apache-2.0", "EPL-1.0"}:                  pass,
	LicensePair{"Apache-2.0", "EPL-2.0"}:                  pass,
	LicensePair{"Apache-2.0", "EUPL-1.1"}:                 pass,
	LicensePair{"Apache-2.0", "EUPL-1.2"}:                 pass,
	LicensePair{"Apache-2.0", "MPL-2.0"}:                  pass,
	LicensePair{"Apache-2.0", "MS-RL"}:                    pass,
	LicensePair{"Apache-2.0", "ODbL-1.0"}:                 pass,
	LicensePair{"Apache-2.0", "OSL-3.0"}:                  pass,
	LicensePair{"Apache-2.0", "Vim"}:                      pass,
	LicensePair{"Apache-2.0", "CDDL-1.0"}:                 pass,
	LicensePair{"Apache-2.0", "CPAL-1.0"}:                 pass,
	LicensePair{"Apache-2.0", "CPL-1.0"}:                  pass,
	LicensePair{"Apache-2.0", "IPL-1.0"}:                  pass,
	LicensePair{"Apache-2.0", "LPL-1.02"}:                 pass,
	LicensePair{"Apache-2.0", "Nokia"}:                    pass,
	LicensePair{"Apache-2.0", "RPSL-1.0"}:                 pass,
	LicensePair{"Apache-2.0", "SISSL"}:                    pass,
	LicensePair{"Apache-2.0", "Sleepycat"}:                pass,
	LicensePair{"Apache-2.0", "SPL-1.0"}:                  pass,
	LicensePair{"Apache-2.0", "Apache-2.0"}:               pass,
	LicensePair{"Apache-2.0", "ECL-2.0"}:                  pass,
	LicensePair{"Apache-2.0", "php-3.01"}:                 pass,
	LicensePair{"ECL-2.0", "LGPL-2.1-only"}:               pass,
	LicensePair{"ECL-2.0", "LGPL-2.1-or-later"}:           pass,
	LicensePair{"ECL-2.0", "LGPL-3.0-only"}:               pass,
	LicensePair{"ECL-2.0", "GPL-2.0-only"}:                fail,
	LicensePair{"ECL-2.0", "GPL-2.0-or-later"}:            pass,
	LicensePair{"ECL-2.0", "GPL-3.0-only"}:                pass,
	LicensePair{"ECL-2.0", "AGPL-3.0-only"}:               pass,
	LicensePair{"ECL-2.0", "Artistic-2.0"}:                pass,
	LicensePair{"ECL-2.0", "CECILL-2.1"}:                  pass,
	LicensePair{"ECL-2.0", "EPL-1.0"}:                     pass,
	LicensePair{"ECL-2.0", "EPL-2.0"}:                     pass,
	LicensePair{"ECL-2.0", "EUPL-1.1"}:                    pass,
	LicensePair{"ECL-2.0", "EUPL-1.2"}:                    pass,
	LicensePair{"ECL-2.0", "MPL-2.0"}:                     pass,
	LicensePair{"ECL-2.0", "MS-RL"}:                       pass,
	LicensePair{"ECL-2.0", "ODbL-1.0"}:                    pass,
	LicensePair{"ECL-2.0", "OSL-3.0"}:                     pass,
	LicensePair{"ECL-2.0", "Vim"}:                         pass,
	LicensePair{"ECL-2.0", "CDDL-1.0"}:                    pass,
	LicensePair{"ECL-2.0", "CPAL-1.0"}:                    pass,
	LicensePair{"ECL-2.0", "CPL-1.0"}:                     pass,
	LicensePair{"ECL-2.0", "IPL-1.0"}:                     pass,
	LicensePair{"ECL-2.0", "LPL-1.02"}:                    pass,
	LicensePair{"ECL-2.0", "Nokia"}:                       pass,
	LicensePair{"ECL-2.0", "RPSL-1.0"}:                    pass,
	LicensePair{"ECL-2.0", "SISSL"}:                       pass,
	LicensePair{"ECL-2.0", "Sleepycat"}:                   pass,
	LicensePair{"ECL-2.0", "SPL-1.0"}:                     pass,
	LicensePair{"ECL-2.0", "Apache-2.0"}:                  pass,
	LicensePair{"ECL-2.0", "ECL-2.0"}:                     pass,
	LicensePair{"ECL-2.0", "php-3.01"}:                    pass,
}

type ConflictResult struct {
	Unknown bool
	Pass    bool
	Message string
}

var licenseConflictMap = map[LicensePair]ConflictResult{}

func InitializeAnalyzer() {
	// 转换“许可证全名变简称”：全部去除空格改为小写，支持无GNU的许可证名
	var longLicenses []string
	var shortLicenses []string
	for longLicense, shortLicense := range licenseLongToShort {
		// 去空格和转为小写
		longLicense = strings.ToLower(strings.ReplaceAll(longLicense, " ", ""))
		longLicenses = append(longLicenses, longLicense)
		shortLicenses = append(shortLicenses, shortLicense)
		// 另存无gnu的版本
		if strings.HasPrefix(longLicense, "gnu") {
			longLicenses = append(longLicenses, longLicense[3:])
			shortLicenses = append(shortLicenses, shortLicense)
		}
	}
	licenseLongToShort = map[string]string{}
	for i := range longLicenses {
		licenseLongToShort[longLicenses[i]] = shortLicenses[i]
	}
	// 转换许可证冲突检测结果
	for licensePair, result := range licenseConflictBaseMap {
		licenseConflictMap[licensePair] =
			ConflictResult{Unknown: false, Pass: strings.HasPrefix(result, pass), Message: result}
	}
	//for licensePair, result := range licenseConflictMap {
	//	fmt.Printf("%+v %+v\n", licensePair, result)
	//}
}

func LicenseLongNameToShort(str string) string {
	return licenseLongToShort[strings.ToLower(strings.ReplaceAll(str, " ", ""))]
}

// CheckLicenseConflictByShortName 判断两个许可证是否相容，参数类型为两个许可证简称字符串
// 第一个参数是自己项目要使用的许可证，第二个参数是要使用的库的许可证
// 返回相容性信息 和 是否确定相容
func CheckLicenseConflictByShortName(mainLicense string, libLicense string) (result ConflictResult) {
	result, known := licenseConflictMap[LicensePair{mainLicense, libLicense}]
	if !known {
		// 未知
		result.Unknown = true
		result.Message = unknown
	}
	return
}

// RecommendByLibraryLicenseShortName 依据依赖库的许可证简称，提供一些推荐许可证
// 参数是一个字符串数组切片，代表所使用的各个库的许可证
// 返回一个长度不大于3的推荐许可证数组切片。
func RecommendByLibraryLicenseShortName(libLicenses []string) (result []string) {
	for _, l1 := range licenseArr {
		noConflict := true
		for _, l2 := range libLicenses {
			conflictResult := CheckLicenseConflictByShortName(l1, l2)
			if !conflictResult.Pass {
				noConflict = false
				break
			}
		}
		if noConflict {
			result = append(result, l1)
		}
	}
	return
}
